### ISSUE TITLE
Gallery Review Feedback

### ISSUE THREAD

**Issue by delsonting** [TribeOS/tribeos-pixel-template#1]
Your template has been approved for the gallery, there are two recommendations to improve the template:

1) [URIEncode](https://developers.google.com/tag-manager/templates/api#encodeuri) data.accountId on line 66 to ensure that the value provided by the user results in a valid url. 
`const url = 'https://at-api.tribeos.io/a/'+data.accountId+'/setup.js';	`

2) On line 68, the setInWindow line does not appear to do anything, consider removing this line (and the corresponding require on line 64) or fixing the behavior.
`var __ta = setInWindow('__ta') || [];`

**Comment by banberina** [comment]
> Your template has been approved for the gallery, there are two recommendations to improve the template:
> 
> 1. [URIEncode](https://developers.google.com/tag-manager/templates/api#encodeuri) data.accountId on line 66 to ensure that the value provided by the user results in a valid url.
>    `const url = 'https://at-api.tribeos.io/a/'+data.accountId+'/setup.js';	`
> 2. On line 68, the setInWindow line does not appear to do anything, consider removing this line (and the corresponding require on line 64) or fixing the behavior.
>    `var __ta = setInWindow('__ta') || [];`

### Thank you for your review, but here's why we can't do those modifications on this code:

1. 'URIEncode' wouldn't be helpful for our developers, because we want it to be easily reachable in order to get some data.
2. __ta variable is valuable for our dev team as well, it is used in a script.

**Comment by delsonting** [comment]
#1 - URI Encoding is necessary here to sanitize the user provided input in data.accountId, this will transform only non-url friendly characters to ensure the url is valid. As currently implemented, if the user provides an account id with a space or a question mark then the resulting url is invalid and the tag fails silently. You can read more about encodeURIComponent in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

#2 - I'm comfortable with this variable if it is being used in the script. 

Please remedy #1 and we can get this submissions approved for the Gallery. Thanks.

**Comment by banberina** [comment]
> #1 - URI Encoding is necessary here to sanitize the user provided input in data.accountId, this will transform only non-url friendly characters to ensure the url is valid. As currently implemented, if the user provides an account id with a space or a question mark then the resulting url is invalid and the tag fails silently. You can read more about encodeURIComponent in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)
> 
> #2 - I'm comfortable with this variable if it is being used in the script.
> 
> Please remedy #1 and we can get this submissions approved for the Gallery. Thanks.

It's updated with encodeURI now, hope it's okay.

**Comment by delsonting** [comment]
Thanks change has been verified and the template has been approved.
